chore: update `yarn.lock` file (#720)
We are seeing workflow failure with,

```
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 35.0.0, but found 36.0.0)
  ERROR      integ.awscli-asset 7.733s
      Command exited with status 1

Snapshot Results: 

Tests:    1 failed, 1 total
Failed: /home/runner/work/awscdk-asset-awscli/awscdk-asset-awscli/test/integ.awscli-asset.ts
Error: Some tests failed!
To re-run failed tests run: integ-runner --update-on-failed
    at main (/home/runner/work/awscdk-asset-awscli/awscdk-asset-awscli/node_modules/@aws-cdk/integ-runner/lib/index.js:10423:13)
```

It looks like our `integ-runner` packages were not updated in `yarn.lock` file with the `latest` flag too. Updating the lock file with this PR.